# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsls < Formula
  desc "A list command for AWS resources"
  homepage "https://github.com/jckuester/awsls"
  version "0.9.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/jckuester/awsls/releases/download/v0.9.0/awsls_0.9.0_darwin_amd64.tar.gz"
    sha256 "33e932c9f532bcca36017131676835f32bda71f7645ba609a2d76176e502c166"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jckuester/awsls/releases/download/v0.9.0/awsls_0.9.0_linux_amd64.tar.gz"
    sha256 "b6e25607af20cf42e332bbf8274cd7b1496dbbca57b3f162ae643a04dffa35d0"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/jckuester/awsls/releases/download/v0.9.0/awsls_0.9.0_linux_armv6.tar.gz"
    sha256 "03d8517db29058735d75cc13d407087d347ae89503760e5929fa6becfcdde118"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jckuester/awsls/releases/download/v0.9.0/awsls_0.9.0_linux_arm64.tar.gz"
    sha256 "f886fb4d6d68c9af38518812df90119b8c644df3b5464e974bf50db728e1aef3"
  end

  def install
    bin.install "awsls"
  end
end
