# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsrm < Formula
  desc "A remove command for AWS resources"
  homepage "https://github.com/jckuester/awsrm"
  version "0.2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jckuester/awsrm/releases/download/v0.2.0/awsrm_0.2.0_darwin_amd64.tar.gz"
      sha256 "f82aa2004b328fd3cda6b5e27220b70c759822138875cd90ceef9911649b7f31"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jckuester/awsrm/releases/download/v0.2.0/awsrm_0.2.0_linux_amd64.tar.gz"
      sha256 "8cbc600a64624c48795546fae2bf93c4573ab66824f10f8afb07d56fb2a7b9ab"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jckuester/awsrm/releases/download/v0.2.0/awsrm_0.2.0_linux_armv6.tar.gz"
      sha256 "80387156fcce8a9e81e977baf027bf34cf8a54204e2931c4368a9082668a7db4"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jckuester/awsrm/releases/download/v0.2.0/awsrm_0.2.0_linux_arm64.tar.gz"
      sha256 "a2923a59a26cb348841254fc86ce3cb48585dd967b5ac55d9d7940922d9bb16d"
    end
  end

  def install
    bin.install "awsrm"
  end
end
