# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsrm < Formula
  desc "A remove command for AWS resources"
  homepage "https://github.com/jckuester/awsrm"
  version "0.2.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jckuester/awsrm/releases/download/v0.2.1/awsrm_0.2.1_darwin_amd64.tar.gz"
      sha256 "b651d1afc926688e6eda319226d15fdf04d140855e4401f2e9effd3269a56c2d"
    end
    if Hardware::CPU.arm?
      url "https://github.com/jckuester/awsrm/releases/download/v0.2.1/awsrm_0.2.1_darwin_arm64.tar.gz"
      sha256 "f2585e03a9acb4537f87b984987c2683764367b17bc4bc150edb6158c7692aff"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jckuester/awsrm/releases/download/v0.2.1/awsrm_0.2.1_linux_amd64.tar.gz"
      sha256 "419ffc813854334781b0d42a65698721ebd7cc19d1444361ce8244818494466f"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jckuester/awsrm/releases/download/v0.2.1/awsrm_0.2.1_linux_armv6.tar.gz"
      sha256 "8cad725b156c64d57a0931fba1ba260ade9a71aab9361f3d29d4de29f100f5c5"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jckuester/awsrm/releases/download/v0.2.1/awsrm_0.2.1_linux_arm64.tar.gz"
      sha256 "587ee300c72f9e4c414afcfc5f118482727d44355cc958805f90a43b4df9f09a"
    end
  end

  def install
    bin.install "awsrm"
  end
end
