# This file was generated by GoReleaser. DO NOT EDIT.
class Awsweeper < Formula
  desc "A tool for cleaning your AWS account"
  homepage "https://github.com/jckuester/awsweeper"
  version "0.11.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jckuester/awsweeper/releases/download/v0.11.0/awsweeper_0.11.0_darwin_amd64.tar.gz"
    sha256 "d964645a5cdeaca6b36244b2a4e598218f018b83d9824053387e612a0f37254d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jckuester/awsweeper/releases/download/v0.11.0/awsweeper_0.11.0_linux_amd64.tar.gz"
    sha256 "ef6c5bc3d72c92470b51a78e761ebd806608e5f53981efa87175a36f4f1ae2ce"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/jckuester/awsweeper/releases/download/v0.11.0/awsweeper_0.11.0_linux_armv6.tar.gz"
    sha256 "e568a0a6e40e657416ac20955e38c886b1bb6c96ba22e6e6d3d4c5a032ac5dfd"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jckuester/awsweeper/releases/download/v0.11.0/awsweeper_0.11.0_linux_arm64.tar.gz"
    sha256 "5f39b176cd5f5514a619db753c4755f63653cb038a135c98102c94a5d9748aaa"
  end

  def install
    bin.install "awsweeper"
  end
end
