# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsweeper < Formula
  desc "A tool for cleaning your AWS account"
  homepage "https://github.com/jckuester/awsweeper"
  version "0.12.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jckuester/awsweeper/releases/download/v0.12.0/awsweeper_0.12.0_darwin_arm64.tar.gz"
      sha256 "86246b952b5cb0e2148d0b8728ba620a158787270f63d2b08bd00756eaafcbfc"

      def install
        bin.install "awsweeper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jckuester/awsweeper/releases/download/v0.12.0/awsweeper_0.12.0_darwin_amd64.tar.gz"
      sha256 "1190ac86d0c8d85ab0dae97e4c24a5bb11f8bf594ca73b001481f35795096a38"

      def install
        bin.install "awsweeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jckuester/awsweeper/releases/download/v0.12.0/awsweeper_0.12.0_linux_armv6.tar.gz"
      sha256 "ba80a9f9cdd620d0f69bd2ca4e422974ade62819fe823d4aef262b91371a370a"

      def install
        bin.install "awsweeper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jckuester/awsweeper/releases/download/v0.12.0/awsweeper_0.12.0_linux_amd64.tar.gz"
      sha256 "eb16da2456bcd84677e5cf89004e372e039a6a9f9acdfceae1bf54b089233ec4"

      def install
        bin.install "awsweeper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jckuester/awsweeper/releases/download/v0.12.0/awsweeper_0.12.0_linux_arm64.tar.gz"
      sha256 "5e1af01ab28e94bfcd695e65e659e4804968e25f198a60f7c2b58fa55975818e"

      def install
        bin.install "awsweeper"
      end
    end
  end
end
