# This file was generated by GoReleaser. DO NOT EDIT.
class Awsweeper < Formula
  desc "A tool for cleaning your AWS account"
  homepage "https://github.com/jckuester/awsweeper"
  version "0.11.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jckuester/awsweeper/releases/download/v0.11.1/awsweeper_0.11.1_darwin_amd64.tar.gz"
    sha256 "c513e54675e7cbfd62bb9e1cba2bc6e6bd97151be7b51b2637ac466585f82e9a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jckuester/awsweeper/releases/download/v0.11.1/awsweeper_0.11.1_linux_amd64.tar.gz"
    sha256 "da28a99ca549c2d9ed9e32d388a89f46610fed9953601240eadf638045fa1ba2"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/jckuester/awsweeper/releases/download/v0.11.1/awsweeper_0.11.1_linux_armv6.tar.gz"
    sha256 "55a3723f0ac08f01294c911bfcfb6cd34ddece7d4300c36c1f1fd7909ad0aeab"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jckuester/awsweeper/releases/download/v0.11.1/awsweeper_0.11.1_linux_arm64.tar.gz"
    sha256 "c2576006f12c9be480b3a2bac5b1c9b4e04720387c3a44b2fe7cd455ef55e64a"
  end

  def install
    bin.install "awsweeper"
  end
end
